version: '3.8'

services:
  helpdesk:
    build:
      context: ./Projetos-xamp/Projeto_helpdesk
    ports:
      - "8080:80"
    volumes:
      - ./Projetos-xamp/Projeto_helpdesk/storage:/var/www/html/storage
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    restart: unless-stopped
